/*
outputs.tf

This file exposes key resource identifiers generated by Terraform.
Using these outputs, you can verify that your static site and CloudFront distribution are set up correctly.

To debug, check the CloudFront domain name and certificate ARN outputs.
*/

output "s3_bucket_name" {
description = "The name of the S3 bucket hosting the static files."
value       = aws_s3_bucket.static_site.bucket
}

output "s3_bucket_arn" {
description = "The ARN of the S3 bucket."
value       = aws_s3_bucket.static_site.arn
}

output "cloudfront_distribution_id" {
description = "The ID of the CloudFront distribution."
value       = aws_cloudfront_distribution.cdn.id
}

output "cloudfront_distribution_domain_name" {
description = "The domain name for the CloudFront distribution."
value       = aws_cloudfront_distribution.cdn.domain_name
}

output "acm_certificate_arn" {
description = "The ARN of the ACM certificate after validation."
value       = aws_acm_certificate_validation.this.certificate_arn
}

output "website_url" {
description = "The website URL (served over HTTPS) via CloudFront."
value       = "https://${var.domain_name}"
}