basePath: /
definitions:
  data.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      updated_at:
        type: string
      user_name:
        type: string
    type: object
  handlers.ApiError:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  handlers.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.TokenResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: API for the ULD Management System
  title: Rest API
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Retrive token for bearer authentication
      parameters:
      - description: Login Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token Response
          schema:
            $ref: '#/definitions/handlers.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ApiError'
      summary: Retrive token for bearer authentication
      tags:
      - Auth
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Create User Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User
          schema:
            $ref: '#/definitions/data.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ApiError'
      summary: Create User
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Get a user by apiKey
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User
          schema:
            $ref: '#/definitions/data.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ApiError'
      security:
      - ApiKeyAuth: []
      summary: Get User by apiKey
      tags:
      - User
securityDefinitions:
  Bearer Authentication:
    description: Please provide a valid JWT token with Bearer prefix
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
